service: bms-notify

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-south-1

functions:
  hello:
    handler: handler.graphql
  regions:
    handler: src/resolvers/regions/index.handler
  cinemas:
    handler: src/resolvers/cinemas/index.handler
  movies:
    handler: src/resolvers/movies/index.handler
  # crons
  update-regions:
    handler: src/crons/update-regions/index.handler
    description: A cron that fetches regions from BMS and puts it in dynamodb
    events:
      - schedule:
          name: bms-notify-update-regions-cron-${self:provider.stage}
          description: A cron that fetches regions from BMS and puts it in dynamodb
          rate: rate(7 days)

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-appsync-offline
  - serverless-offline

custom:
  webpack:
    packager: 'yarn' # Defaults to npm
  appsync-emulator:
    buildPrefix: .webpack/service
  appsync-offline:
    port: 62222
    dynamodb:
      client:
        # if endpoint is provided, no local database server is started and and appsync connects to the endpoint - e.g. serverless-dynamodb-local
        endpoint: 'http://localhost:8000'
  appSync:
    name: bms-notify
    authenticationType: API_KEY
    mappingTemplates:
      - dataSource: regionsDataSource
        type: Query
        field: regions
        request: hello-request-mapping-template.txt
        response: hello-response-mapping-template.txt
      - dataSource: cinemasDataSource
        type: Query
        field: cinemas
        request: hello-request-mapping-template.txt
        response: hello-response-mapping-template.txt
      - dataSource: moviesDataSource
        type: Query
        field: movies
        request: hello-request-mapping-template.txt
        response: hello-response-mapping-template.txt
    schema: # defaults schema.graphql
    serviceRole: AppSyncServiceRole
    dataSources:
      - type: AWS_LAMBDA
        name: regionsDataSource
        description: 'Lambda DataSource'
        config:
          functionName: regions # The function name in your serverless.yml. Ignored if lambdaFunctionArn is provided.
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] } # Where AppSyncLambdaServiceRole is an IAM role defined in Resources
      - type: AWS_LAMBDA
        name: cinemasDataSource
        description: 'Lambda DataSource'
        config:
          functionName: cinemas
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }
      - type: AWS_LAMBDA
        name: moviesDataSource
        description: 'Lambda DataSource'
        config:
          functionName: movies
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }

resources:
  Resources:
    # AppSync lambda role
    AppSyncLambdaServiceRole:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: 'Lambda-${self:custom.appSync.serviceRole}'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service:
                  - 'appsync.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
        Policies:
          - PolicyName: 'Lambda-${self:custom.appSync.serviceRole}-Policy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'lambda:invokeFunction'
                  Resource:
                    - 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-*'
