# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.14

    working_directory: ~/repo

    steps:
      - checkout

      # # restore yarn global cache
      # - restore_cache:
      #     keys:
      #       - v1-yarn-global-cache-{{ .Branch }}-{{ .Environment.CIRCLE_TAG }}-{{ .Revision }}
      #       - v1-yarn-global-cache-{{ .Branch }}-{{ .Environment.CIRCLE_TAG }}
      # # restore node_modules cache
      # - restore_cache:
      #     keys:
      #       - v2-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v2-dependencies-

      - run:
          name: Build dependencies
          command: sudo apt-get install libzmq3-dev

      - run: yarn install

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v2-dependencies-{{ checksum "package.json" }}
      # - save_cache:
      #     key: v1-yarn-global-cache-{{ .Branch }}-{{ .Environment.CIRCLE_TAG }}-{{ .Revision }}
      #     paths:
      #       - ~/.cache/yarn/

      # Type check & Lint
      - run:
          name: Type check
          command: yarn type-check
      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Deploy
          command: ~/repo/.circleci/deploy.sh
